[project]
name = "flaskr"
version = "1.0.0"
description = "Python Learning Project - Flask com SQLite3."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"